window:
  decorations: none
  startup_mode: Maximized
  dynamic_title: true

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Retina
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: FiraCode Nerd Font Mono
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font Mono
    style: Bold Italic
  size: 15.0
  builtin_box_drawing: true

draw_bold_text_with_bright_colors: true

selection:
  # copy selected text to the primary clipboard
  save_to_clipboard: true

key_bindings:
  # Option + Left-Arrow: previous word
  - { key: Left,  mods: Alt, chars: "\x1bb" }
  # Option + Right-Arrow: next word
  - { key: Right, mods: Alt, chars: "\x1bf" }

schemes:
  ayu_mirage: &ayu_mirage
    primary:
      background: '#202734'
      foreground: '#CBCCC6'
    normal:
      black: '#191E2A'
      red: '#FF3333'
      green: '#BAE67E'
      yellow: '#FFA759'
      blue: '#73D0FF'
      magenta: '#FFD580'
      cyan: '#95E6CB'
      white: '#C7C7C7'
    bright:
      black: '#686868'
      red: '#F27983'
      green: '#A6CC70'
      yellow: '#FFCC66'
      blue: '#5CCFE6'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  ayu_dark: &ayu_dark
    primary:
      background: '#0A0E14'
      foreground: '#B3B1AD'
    normal:
      black: '#01060E'
      red: '#EA6C73'
      green: '#91B362'
      yellow: '#F9AF4F'
      blue: '#53BDFA'
      magenta: '#FAE994'
      cyan: '#90E1C6'
      white: '#C7C7C7'
    bright:
      black: '#686868'
      red: '#F07178'
      green: '#C2D94C'
      yellow: '#FFB454'
      blue: '#59C2FF'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  base16_black_metal_bathory: &base16_black_metal_bathory
    primary:
      background: '0x000000'
      foreground: '0xc1c1c1'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x000000'
      cursor: '0xc1c1c1'
    normal:
      black:   '0x000000'
      red:     '0x5f8787'
      green:   '0xfbcb97'
      yellow:  '0xe78a53'
      blue:    '0x888888'
      magenta: '0x999999'
      cyan:    '0xaaaaaa'
      white:   '0xc1c1c1'
    bright:
      black:   '0x333333'
      red:     '0xaaaaaa'
      green:   '0x121212'
      yellow:  '0x222222'
      blue:    '0x999999'
      magenta: '0x999999'
      cyan:    '0x444444'
      white:   '0xc1c1c1'

  base16_brewer: &base16_brewer
    primary:
      background: '0x0c0d0e'
      foreground: '0xb7b8b9'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x0c0d0e'
      cursor: '0xb7b8b9'
    normal:
      black:   '0x0c0d0e'
      red:     '0xe31a1c'
      green:   '0x31a354'
      yellow:  '0xdca060'
      blue:    '0x3182bd'
      magenta: '0x756bb1'
      cyan:    '0x80b1d3'
      white:   '0xb7b8b9'
    bright:
      black:   '0x737475'
      red:     '0xe6550d'
      green:   '0x2e2f30'
      yellow:  '0x515253'
      blue:    '0x959697'
      magenta: '0xdadbdc'
      cyan:    '0xb15928'
      white:   '0xfcfdfe'

  base16_bright: &base16_bright
    primary:
      background: '0x000000'
      foreground: '0xe0e0e0'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x000000'
      cursor: '0xe0e0e0'
    normal:
      black:   '0x000000'
      red:     '0xfb0120'
      green:   '0xa1c659'
      yellow:  '0xfda331'
      blue:    '0x6fb3d2'
      magenta: '0xd381c3'
      cyan:    '0x76c7b7'
      white:   '0xe0e0e0'
    bright:
      black:   '0xb0b0b0'
      red:     '0xfc6d24'
      green:   '0x303030'
      yellow:  '0x505050'
      blue:    '0xd0d0d0'
      magenta: '0xf5f5f5'
      cyan:    '0xbe643c'
      white:   '0xffffff'

  base16_chalk: &base16_chalk
    primary:
      background: '0x151515'
      foreground: '0xd0d0d0'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x151515'
      cursor: '0xd0d0d0'
    normal:
      black:   '0x151515'
      red:     '0xfb9fb1'
      green:   '0xacc267'
      yellow:  '0xddb26f'
      blue:    '0x6fc2ef'
      magenta: '0xe1a3ee'
      cyan:    '0x12cfc0'
      white:   '0xd0d0d0'
    bright:
      black:   '0x505050'
      red:     '0xeda987'
      green:   '0x202020'
      yellow:  '0x303030'
      blue:    '0xb0b0b0'
      magenta: '0xe0e0e0'
      cyan:    '0xdeaf8f'
      white:   '0xf5f5f5'

  base16_dracula: &base16_dracula
    primary:
      background: '0x282936'
      foreground: '0xe9e9f4'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x282936'
      cursor: '0xe9e9f4'
    normal:
      black:   '0x282936'
      red:     '0xea51b2'
      green:   '0xebff87'
      yellow:  '0x00f769'
      blue:    '0x62d6e8'
      magenta: '0xb45bcf'
      cyan:    '0xa1efe4'
      white:   '0xe9e9f4'
    bright:
      black:   '0x626483'
      red:     '0xb45bcf'
      green:   '0x3a3c4e'
      yellow:  '0x4d4f68'
      blue:    '0x62d6e8'
      magenta: '0xf1f2f8'
      cyan:    '0x00f769'
      white:   '0xf7f7fb'

  base16_flat: &base16_flat
    primary:
      background: '0x2c3e50'
      foreground: '0xe0e0e0'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x2c3e50'
      cursor: '0xe0e0e0'
    normal:
      black:   '0x2c3e50'
      red:     '0xe74c3c'
      green:   '0x2ecc71'
      yellow:  '0xf1c40f'
      blue:    '0x3498db'
      magenta: '0x9b59b6'
      cyan:    '0x1abc9c'
      white:   '0xe0e0e0'
    bright:
      black:   '0x95a5a6'
      red:     '0xe67e22'
      green:   '0x34495e'
      yellow:  '0x7f8c8d'
      blue:    '0xbdc3c7'
      magenta: '0xf5f5f5'
      cyan:    '0xbe643c'
      white:   '0xecf0f1'

  base16_material_palenight: &base16_material_palenight
    primary:
      background: '0x292d3e'
      foreground: '0x959dcb'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x292d3e'
      cursor: '0x959dcb'
    normal:
      black:   '0x292d3e'
      red:     '0xf07178'
      green:   '0xc3e88d'
      yellow:  '0xffcb6b'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x89ddff'
      white:   '0x959dcb'
    bright:
      black:   '0x676e95'
      red:     '0xf78c6c'
      green:   '0x444267'
      yellow:  '0x32374d'
      blue:    '0x8796b0'
      magenta: '0x959dcb'
      cyan:    '0xff5370'
      white:   '0xffffff'

  base16_nord: &base16_nord
    primary:
      background: '0x2e3440'
      foreground: '0xe5e9f0'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x2e3440'
      cursor: '0xe5e9f0'
    normal:
      black:   '0x2e3440'
      red:     '0xbf616a'
      green:   '0xa3be8c'
      yellow:  '0xebcb8b'
      blue:    '0x81a1c1'
      magenta: '0xb48ead'
      cyan:    '0x88c0d0'
      white:   '0xe5e9f0'
    bright:
      black:   '0x4c566a'
      red:     '0xd08770'
      green:   '0x3b4252'
      yellow:  '0x434c5e'
      blue:    '0xd8dee9'
      magenta: '0xeceff4'
      cyan:    '0x5e81ac'
      white:   '0x8fbcbb'

  base16_phd: &base16_phd
    primary:
      background: '0x061229'
      foreground: '0xb8bbc2'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x061229'
      cursor: '0xb8bbc2'
    normal:
      black:   '0x061229'
      red:     '0xd07346'
      green:   '0x99bf52'
      yellow:  '0xfbd461'
      blue:    '0x5299bf'
      magenta: '0x9989cc'
      cyan:    '0x72b9bf'
      white:   '0xb8bbc2'
    bright:
      black:   '0x717885'
      red:     '0xf0a000'
      green:   '0x2a3448'
      yellow:  '0x4d5666'
      blue:    '0x9a99a3'
      magenta: '0xdbdde0'
      cyan:    '0xb08060'
      white:   '0xffffff'

  base16_rebecca: &base16_rebecca
    primary:
      background: '0x292a44'
      foreground: '0xf1eff8'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x292a44'
      cursor: '0xf1eff8'
    normal:
      black:   '0x292a44'
      red:     '0xa0a0c5'
      green:   '0x6dfedf'
      yellow:  '0xae81ff'
      blue:    '0x2de0a7'
      magenta: '0x7aa5ff'
      cyan:    '0x8eaee0'
      white:   '0xf1eff8'
    bright:
      black:   '0x666699'
      red:     '0xefe4a1'
      green:   '0x663399'
      yellow:  '0x383a62'
      blue:    '0xa0a0c5'
      magenta: '0xccccff'
      cyan:    '0xff79c6'
      white:   '0x53495d'

  base16_solarized_dark: &base16_solarized_dark
    primary:
      background: '0x002b36'
      foreground: '0x93a1a1'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x002b36'
      cursor: '0x93a1a1'
    normal:
      black:   '0x002b36'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0x6c71c4'
      cyan:    '0x2aa198'
      white:   '0x93a1a1'
    bright:
      black:   '0x657b83'
      red:     '0xcb4b16'
      green:   '0x073642'
      yellow:  '0x586e75'
      blue:    '0x839496'
      magenta: '0xeee8d5'
      cyan:    '0xd33682'
      white:   '0xfdf6e3'

  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'

  new_moon: &new_moon
    primary:
      background: '#2D2D2D'
      foreground: '#B3B9C5'
    normal:
      black: '#2D2D2D'
      red: '#F2777A'
      green: '#92D192'
      yellow: '#FFD479'
      blue: '#6AB0F3'
      magenta: '#E1A6F2'
      cyan: '#76D4D6'
      white: '#B3B9C5'
    bright:
      black: '#777C85'
      red: '#F2777A'
      green: '#76D4D6'
      yellow: '#FFEEA6'
      blue: '#6AB0F3'
      magenta: '#E1A6F2'
      cyan: '#76D4D6'
      white: '#FFFFFF'

  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    normal:
      black:   '0x3B4252'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x88C0D0'
      white:   '0xE5E9F0'
    bright:
      black:   '0x4C566A'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x8FBCBB'
      white:   '0xECEFF4'

  tokyo_night: &tokyo_night
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo_night_storm: &tokyo_night_storm
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors
colors: *ayu_dark

